spring.application.name=ProjectApiApplication

# M\u1EB7c \u0111\u1ECBnh s\u1EED d\u1EE5ng Hikari Connection Pool
spring.datasource.url = jdbc:mysql://localhost:3306/projectdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = root

# L\u00E0 m\u1ED9t class trong Hibernate, d\u00F9ng \u0111\u1EC3 ch\u1EC9 cho Hibernate bi\u1EBFt c\u00E1ch sinh c\u00E2u l\u1EC7nh SQL ph\u00F9 h\u1EE3p v\u1EDBi database c\u1EE5 th\u1EC3
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
# Ch\u1EC9 n\u00EAn c\u1EA5u h\u00ECnh dll auto l\u1EA7n \u0111\u1EA7u \u0111\u1EC3 t\u1EA1o b\u1EA3ng, sau \u0111\u00F3 n\u00EAn kh\u00F3a
# \u0111\u1EC3 tr\u00E1nh vi\u1EC7c t\u1EF1 \u0111\u1ED9ng t\u1EA1o b\u1EA3ng ngo\u00E0i \u00FD mu\u1ED1n tr\u00EAn m\u00F4i tr\u01B0\u1EDDng production
spring.jpa.hibernate.ddl-auto = update

# C\u00E1c th\u00F4ng b\u00E1o log t\u1EEB Spring Security c\u00F3 m\u1EE9c \u0111\u1ED9 DEBUG tr\u1EDF l\u00EAn (DEBUG, INFO, WARN, ERROR) s\u1EBD \u0111\u01B0\u1EE3c ghi l\u1EA1i.
# th\u00F4ng th\u01B0\u1EDDng hi\u1EC3n th\u1ECB ra console
logging.level.org.springframework.security=DEBUG

# C\u1ED5ng ho\u1EA1t \u0111\u1ED9ng
server.port=8088

# Show c\u00E2u l\u1EC7nh sql ra console \u0111\u1EC3 theo d\u00F5i
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
